apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplejavaapp
  labels:
    app: samplejavaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplejavaapp
  template:
    metadata:
      labels:
        app: samplejavaapp
    spec:
      containers:
      - name: samplejavaapp
        image: lerndevops/samplejavaapp
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: samplejavaapp-svc
spec:
  type: NodePort
  selector:
    app: samplejavaapp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
